### ISSUE TITLE
Our Slack has "Gone to the Dogs"

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#109]
The icon and the amount of parrot gifs are out of control.

**Comment by grahamearley** [comment]
:parrot_fieri:

**Comment by grahamearley** [comment]
Deprioritize

**Comment by brennan724** [comment]
I think the title should be changed to "Gone to the Parrots"

**Comment by grahamearley** [comment]
Yeah, file an issue for that

**Comment by shoemakerc** [comment]
![run](https://media.tenor.co/images/20674e2d0b63bc28d7712a3ea459097f/raw "run parrot run!")

**Comment by cpimhoff** [comment]
Now that our github issue tracker has also "gone to the parrots", I'm at least content with the consistency.
