### ISSUE TITLE
Remove text files that denoted what certain folders should be

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#113]
There aren't needed anymore.

- `Assets/Editor/editor.txt`
- `Assets/Framework/framework.txt`
etc.

**Comment by grahamearley** [comment]
File this under DELETE SPREE, along with #96

**Comment by grahamearley** [comment]
Also delete Documentation folder from the root directory

**Comment by cpimhoff** [comment]
resolved on PR #130
