### ISSUE TITLE
Automate linking of Twine nodes to `Associated Twine Node` components

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#118]
I'm thinking that we should make the first dropdown try to go to a node matching the name of the component's GameObject. Otherwise, default to index 0.

**Comment by brennan724** [comment]
I like this idea, especially since people will probably name them the same things.  We'll have to make sure that if we are searching by name, then we get the appropriate object (get a twine node when we want a twine node, and not end up with the in-game object instead).

**Comment by grahamearley** [comment]
Done, in #119! 💥
