### ISSUE TITLE
Misleading error on Annotation

### ISSUE THREAD

**Issue by Donahuec** [mjavaly/Prairie#122]
When creating an area annotation without  isTrigger set, the inspector has an error saying that it requires a collider, but the button says to 'Set to Trigger.' This is misleading, as both types of annotations require a collider, and it doesn't mention anything about isTrigger in the warning.

**Comment by cpimhoff** [comment]
Just looked at mah code - yeah that sucks. I'll fix.

**Comment by cpimhoff** [comment]
resolved on PR #130
