### ISSUE TITLE
Prompt for Deactivated Interactions

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#135]
If an interaction is deactivated, the prompt could become out of date - or at the very least, could still be displayed even though all the interactions no longer apply to an object. In more abstract terms, there is no way to define a change to the prompt as the editor of the game.

Now that we've sorta dropped "repeatable" in many of our interactions, maybe this isn't a big deal? But I feel like it kinda is.

**Comment by cpimhoff** [comment]
example:
> Opening the door to the big control room also plays music and turns on the lights. It's a dramatic moment. These interactions (the door) is defined by the editor as not repeatable.
> The player moves back to the door, it still says "Click to Open Door" even though clicking will now doing nothing.

**Comment by grahamearley** [comment]
Hmm. Interesting point. Another conundrum that relates to your example:

What if you want the prompt to say "Open the door" when the door is closed and "Close the door" when the door is open?

I'm not sure how we could make prompts more conditional, but I don't think this is a use-case we should ignore.

**Comment by cpimhoff** [comment]
Dear Graham,
Your example is SO much better than mine.

**Comment by Donahuec** [comment]
This is something I have thought a little bit about (also specifically with doors). I think I have a bit of an idea of how to implement having cycling prompts, as well as disabling them. I can take a stab at implementing it this weekend if you'd like.

**Comment by grahamearley** [comment]
What's your idea? 

I think cycling prompts could solve the door thing, if by "cycling" you mean there are `n` prompts and prompt `i` always shows up on the `i % n`th interaction.

But there are still more complex cases like what Charlie said, where you might want your prompt to say *Click to open the door and play some crazy music* and then next time you interact with the door, it doesn't have the audio interaction. So you want it to say *Close the door.* Then you want it to just say *Open the door* and then *Close the door* and then just cycle between those forever.

How would you handle these sorts of "irregular" cycles that have a few different states to go through before they reach a "true" cycle that goes through individual "states" in order (like *Close*, *Open*, *Close*, ..., etc)

**Comment by cpimhoff** [comment]
I agree with @grahamearley that I'd like to hash out @Donahuec's potential solution before we jump to implementation, since it could, in theory, involve some fair amount of complexity.

**Comment by Donahuec** [comment]
I'll hash out my idea later tonight. Right now I'm focusing on trying to figure out CG homework that i missed all the classes about...

**Comment by Donahuec** [comment]
Thinking about things being more complex, you're right in that we might want to consider exactly how complex we want to let the user's make it. I'll think about it some more, and we should just discuss it on Sunday and work from there.

**Comment by mjavaly** [comment]
One idea is to give Prompt two text fields - one for before the PerformAction() method is called from the Interaction (for a door, "Click to Open") and then one for afterward ("Click to Close"). Just an idea - I'm pretty sure two components attached to an object can talk to each other, so it may not require as complex an implementation as we thought.

**Comment by grahamearley** [comment]
To keep things relatively simple, we'll just offer 2-cycles (mostly for toggley things and doors)

**Comment by cpimhoff** [comment]
- Cycles were offered on #147 
- Twine Prompts were offered on #151
