### ISSUE TITLE
Allow Annotations to be turned on/off (globally)

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#140]
Austin suggested that we allow users to turn on/off annotations.

To do this, we could add a boolean checkbox to the Prairie Player, called `Annotations Enabled` or something like that. Then every time we `Interact()` with an `Annotation`, we can check if annotations are enabled before showing the GUI.

**Comment by cpimhoff** [comment]
I'll crush.

**Comment by Donahuec** [comment]
Should we make a way to toggle it in game, or allow that as about option?

**Comment by cpimhoff** [comment]
My intention was to make it toggleable from editor as a first step - we can hash out how exactly we want that lever pulled at runtime if need be.

**Comment by grahamearley** [comment]
DONE in PR #142
