### ISSUE TITLE
Escaping Tumble! (and maybe make it better???)

### ISSUE THREAD

**Issue by Donahuec** [mjavaly/Prairie#145]
Currently the mouse click to escape tumble requires the mouse to be on the item, which is problematic if you have rotated the object out of the scope of the mouse, then you cannot escape it without rotating it back in. We should change this to escape on any left mouse click.

Some other potential changes:
- Currently some (all?) objects rotate painfully slowly
-Potentially make it so an object gets picked up and tumbled a fixed distance from the player? Right now tumble seems not so nice for any instance where an item is on a surface or close to other things (so most cases, since there won't be a lot of floating cubes).

**Comment by brennan724** [comment]
Matt, is this done now?

**Comment by mjavaly** [comment]
I sped up rotation speed, and bound the escape key to exit. I want to test the fixed distance thing a little more but then we should be good to go.

**Comment by brennan724** [comment]
Okay, cool.  I just wanted to check in case this was able to be closed (apparently not yet).

**Comment by brennan724** [comment]
PR #160
