### ISSUE TITLE
Prompts on Twine nodes

### ISSUE THREAD

**Issue by Donahuec** [mjavaly/Prairie#146]
We should consider making it so that if there are multiple twine nodes associated with an object, and no other interactions, that the prompt only shows up when a twine interaction is currently available. Maybe a long-shot, but we could consider making it so that the prompt could be specific to the current twine node as well.

For example, in the demo we were making, there were three different meals, and you went and interacted with the table for all of them. The table had the prompt 'eat meal', but even when it was not an option to currently eat a meal (you had to go do some work before supper time), the prompt still appeared. It would be great if it did not appear when the current twine node was not a parent of one of the associated twine nodes.

It would also be cool if we could attach prompts to the speciifc twine nodes in such cases, so you could have the prompts 'eat breakfast', 'eat dinner', 'eat supper', but that also seems low priority.

**Comment by cpimhoff** [comment]
I'm happy to field this.

**Comment by grahamearley** [comment]
^ Make the Prompt component have multiple fields if there are multiple associated Twine nodes (so there is one prompt per TwineNode). Then make a check for which node has an active parent when drawing the prompt (and if no active parent, no prompt!!)

**Comment by cpimhoff** [comment]
Resolved on #151
