### ISSUE TITLE
Changes not always saved/ recognized

### ISSUE THREAD

**Issue by Donahuec** [mjavaly/Prairie#155]
It seems that Unity has some issues recognizing some changes in the custom inspectors as changes to the scene, and then fails to save them. If you do something that Unity does recognize as a change, such as adding a new game object, the changes get saved. This only seems to happen some of the time, and is only noticeable upon exiting Unity and reopening it. 

For example, if you add an annotation to something, and later change it to an area annotation, if you do nothing to the scene afterwards, it might not be recognized as a change, and subsequently not saved.

**Comment by cpimhoff** [comment]
Scenes are the only Unity asset that have to be manually saved, no?

Is this a problem that happens even if the scene is explicitly saved?

**Comment by brennan724** [comment]
yes, it's still a problem when the scene (and the project) is explicitly saved.

**Comment by cpimhoff** [comment]
WOWZERS BOWSERS we have been doing this wrong...

**Comment by cpimhoff** [comment]
Relevant reading:
- https://docs.unity3d.com/ScriptReference/EditorUtility.SetDirty.html
- https://docs.unity3d.com/ScriptReference/Undo.RecordObject.html

I'll start working on this soon. Good news is that we'll get undo support for free with this!

**Comment by grahamearley** [comment]
👏 !!! Good find Charlie!!

**Comment by cpimhoff** [comment]
Resolved via PR #165

**Comment by cpimhoff** [comment]
Closed on #165
