### ISSUE TITLE
Removing Indices Based Storage on ATN and ATN-Editor

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#158]
The ATN should just directly hold refs to the associated twine node game objects. The editor should bind them correctly.

No indices should be serialized, as they are non-consistent between loads of a scene.

**Comment by cpimhoff** [comment]
@grahamearley could you get this done as soon as possible? My bugfix (#155) will also require editing `ATNEditor`.

I'm still going to get started on my fix - just worried about a merge conflict during the code freeze 💻❄ crunch.

**Comment by cpimhoff** [comment]
Note that a change to `ATNEditor` will likely be in conflict with #165.

**Comment by grahamearley** [comment]
see #169
