### ISSUE TITLE
twison

### ISSUE THREAD

**Issue by shawngraham** [mjavaly/Prairie#182]
Hi!

Great work. As I go through the tutorial, there seems to be an issue with loading a new Twine story format. In Chrome, I kept getting a time-out error when I tried to load the twison.js file. However, in Firefox, all was fine. I don't know if this is me, or Chrome, but thought I'd mention it.

Thanks!
Shawn

**Comment by apjmason** [comment]
Hi Shawn,

Thanks for taking Prairie through its paces! Version two is in active development by a new team of students in a forked repo right now with lots of new features. I'll make sure they've seen this and address it, at least in the documentation.

Austin

**Comment by shawngraham** [comment]
thanks! i closed this because I saw that I'd already left a previous issue. By the way, I'll probably have a handful of students give Prairie a try too this coming month as part of our class ([https://shawngraham.github.io/hist3812w18/](https://shawngraham.github.io/hist3812w18/ ))
