### ISSUE TITLE
Rename `PlayAudioInteraction` to `AudioInteraction`

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#31]
The rest of the interactions don't have a verb-noun structure (like "Start Slideshow") so I think we should remove the verb from this interaction to keep it consistent with the others.

**Comment by cpimhoff** [comment]
I fully agree with this change.

##### Effects on Existing
- This is a non-breaking API change, nothing referencing this by class name.
- Unity prototyping demos references to `PlayAudioInteraction` would need to be updated to `AudioInteraction`.

**Comment by cpimhoff** [comment]
Resolved on PR #35.
