### ISSUE TITLE
Handle multiple interactions on an item gracefully

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#37]
What happens if you add multiple interactions to an item? Are there multiple prompts?

You can use a `TriggerInteraction` to do multiple interactions nicely, but that might not be a user's first intuition.

**Comment by grahamearley** [comment]
The only problem is that the first interaction is the only one whose prompt is displayed

**Comment by cpimhoff** [comment]
Prompt collision is solved in PR #65.

Multiple interactions are handled (in part) in PR #65, by splitting up inputs for annotation based interactions (`Annotation`, `Slideshow`) from purely interactive types (`NextTwine`, `Toggle`, `Swivel`, etc).
