### ISSUE TITLE
`NextTwineNode` select node from dropdown

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#50]
So much simpler (and type-safer) than the current "select any GameObject in your hierarchy".

---------
It'd be great to have a generic GUI function like this which draws a ~~checkbox~~ dropdown menu and returns the value selected.

      static Value GUICheckbox(Value[] options)

That way we could reuse this across lots of our components.

**Comment by shoemakerc** [comment]
Per our meeting yesterday, we agreed that the implementation of this function would likely only be useful for choosing available nodes to go into our `NextTwineNodeInteraction` (or whatever other name we will change it to).  I have localized the implementation in a new `NextTwineNodeInteractionEditor` script in my working branch.

---

So the issue I've been facing (and what has been keeping me from pulling in my code) is getting a node that is selected from the dropdown to be automatically placed into the `nextTwineNodeObject` of the `NextTwineNodeInteraction` instance.  As far as I know, Unity can't cast `TwineNode` objects into `GameObjects`, both implicitly and explicitly, so I've been unable to assign whatever node is selected into `nextTwineNodeObject`, to which we've so far been assigning nodes by dragging and dropping the appropriate node into a field.

The only solution I can see to this is somehow refactoring `NextTwineNodeInteraction.cs` to change our current system of calling the `TwineNode` component of a `nextTwineNodeObject` and activating it.  I could play with `NextTwineNodeInteraction.cs` to be compatible with the dropdowns, though if not I think we'd be better off revisiting this at a later time, which honestly I'd be fine with, as I've been spending way too much time on this and would probably be better off moving on to other work.

**Comment by grahamearley** [comment]
Is there a way to make the dropdown show all child GameObjects of a TwineNode (the ones with a `TwineNode` component)? And then when you access the GameObject in the menu, you can use `object.GetComponent<TwineNode>()` to get the TwineNode if you need it.

You should be able to access the children GameObjects of a TwineNode object using `twineNode.children`. This will give an array of GameObjects that all have a `TwineNode` component and will be valid input in the Next Twine Node Object field.

**Comment by grahamearley** [comment]
Boom. Thanks #89
