### ISSUE TITLE
Clarify which Standard Assets (and even which Prairie assets) are required in Linking Prairie

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#51]
I think all we need from Standard Assets is "Characters" (and its dependencies)?

We need a wiki page for linking Prairie to a Unity project.

**Comment by brennan724** [comment]
How do we link Prairie to a Unity project (aside from importing the whole file structure)?

**Comment by cpimhoff** [comment]
Based on the fact that the Unity market just copies in packages of assets into your project, I think there's no method of "linking" an external dependencies.

I will write some documentation on how it stands right now -- and maybe look into if there's a better way moving forward.

**Comment by cpimhoff** [comment]
Documentation located at:
https://github.com/mjavaly/Prairie/wiki/Importing-Prairie-into-a-Unity-Project

but we should move some built in prefabs (such as _Player_ out of `Prototype` and into `Framework/Prefabs`)
