### ISSUE TITLE
Swivel is a bit off

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#53]
`SwivelInteraction` rotates a bit off of what a proper door would.

**Comment by cpimhoff** [comment]
might be able to fix this just a tad by increasing whatever the location of our '_pivot point_' is.

**Comment by cpimhoff** [comment]
@mjavaly did you mention that you were able to fix this?

**Comment by mjavaly** [comment]
Yep! Just waiting for your GUI/player changes to be pulled in.

**Comment by cpimhoff** [comment]
Alrighty, are we all set for this now?

**Comment by mjavaly** [comment]
We are. I just made a PR for it, along with some other things.

**Comment by cpimhoff** [comment]
Closed and merged via #78
