### ISSUE TITLE
Refactoring Player, Prompt, and GUI drawing

### ISSUE THREAD

**Issue by Donahuec** [mjavaly/Prairie#59]
Refactor player onGUI method the handle interactions and annotations separately, as well as change how prompts work

**Comment by cpimhoff** [comment]
#### To stub out
* Player indirectly draws prompt, summary. Directly draws toolbar.
* `Player.areaAnnotationsInBounds` property (for coordination with annotations with area trigger)
* `AnnotationInteraction.hasSummary` and `AnnotationInteraction.drawSummary()`

* required component `Prompt`
    * remove drawing "press F to.." from `Player`
* refactor player `highlightedObject` tracking

* refactor `setPlayerFrozen(bool)` to `Player.setCanMove(bool)`
* add `Player.setDrawGUI(bool)`

**Comment by cpimhoff** [comment]
- `FirstPersonInteractor` 
    -  `private void drawToolbar(List<AnnotationInteraction> annotations)`

**Comment by grahamearley** [comment]
While we're at it, we should include TwineNode text drawing in here too. 

It's possible for there to be lots of GUIs being drawn on the player's screen and we should make sure there's no overlap or ugliness!

**Comment by cpimhoff** [comment]
## API Changes

#### Manipulating the Player through Interactions
Freezing the player can no longer be done via the extension method. Interactions must get a reference to the player through `GetPlayer()` then use `player.SetCanMove(bool)`.

This is inline with the similar action of stopping GUI drawing for the player `player.SetDrawsGUI(bool)`

    - removed `FirstPersonInteractor`**:** `public void SetPlayerIsFrozen(bool)`
    - removed `Interaction`**:** `public void SetPlayerIsFrozen(bool)`
    - added `FirstPersonInteractor`**:** `public void SetCanMove(bool)`
    - added `public void SetDrawsGUI(bool)`
    - added `Interaction`**:** `public void GetPlayer()`

**Comment by cpimhoff** [comment]
Implemented and documented in PR #65.
