### ISSUE TITLE
Annotation Summary

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#69]
### Annotation drawing Summary
Annotations must be given a summary field and draw it to screen (if it exists) inside of `Annotation.DrawSummary()`.

> Once this is implemented, it should auto-magic-ally be incorporated by `FirstPersonInteractor`. See #65 for information on the changes made to stub this function.

**Comment by Donahuec** [comment]
I've implemented the basics of this. I'm still playing around with some little details, will probs do a pull request after meeting with @mjavaly tomorrow
