### ISSUE TITLE
Prune old Branches

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#77]
We should start deleting old branches after they've been merged into `master`.

No need to keep a bunch of these around...

**Comment by grahamearley** [comment]
Just pruned all my merged `graham/...` branches!

**Comment by brennan724** [comment]
Pruned mine as well

**Comment by Donahuec** [comment]
pruned all of mine earlier too

**Comment by cpimhoff** [comment]
I think we should get in the habbit of deleting the branch after merge. Github even suggests to do so after you click 'merge'
