### ISSUE TITLE
"Next Twine Node Interaction" is a confusing name

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#79]
(note from user demo)

**Comment by grahamearley** [comment]
> Also, the surprise entrance of a Prompt component was confusing to some. Is there some way to make that more obvious? (or to fill in sensible defaults for prompts?)

Refactored this concern into another issue (#82)

**Comment by cpimhoff** [comment]
Maybe `ProgressTwineStory`? I don't know...
Anybody else?

**Comment by grahamearley** [comment]
Folding this into #83
