### ISSUE TITLE
Add debug.DrawRay to Interactor

### ISSUE THREAD

**Issue by apjmason** [mjavaly/Prairie#80]
Could we add debug.drawray so the raycast is visible in the scene window?

https://docs.unity3d.com/ScriptReference/Debug.DrawRay.html

**Comment by grahamearley** [comment]
Would be a good UI option to let game creators see how far out the ray cast goes from the interactor

**Comment by cpimhoff** [comment]
`OnDrawGizmosSelected()` inside `FirstPersonInteractor` seems like a good candidate to perform this drawing.

**Comment by cpimhoff** [comment]
resolved on PR #130
