### ISSUE TITLE
Prompt Sensible Defaults on Addition

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#82]
From user testing:
> The surprise entrance of a Prompt component was confusing to some. Is there some way to make that more obvious? (or to fill in sensible defaults for prompts?)

**Comment by cpimhoff** [comment]
I have an idea for how to aid this.

When the user adds an interaction, and the prompt is auto-added, it is populated with a sensible default based on the interaction added.

This default can be overridden at will, this is only an auto populated default.

**Comment by cpimhoff** [comment]
See PR #84

**Comment by cpimhoff** [comment]
Defaults provided via PR #84

**Comment by brennan724** [comment]
Here is a possible way to get around this issue.  Get rid of the prompt of 'press whatever to do stuff', and just put a glow/halo around the object that is being focused on.  Similar to how prompt is automatically put on, you just put the halo on.  The video below shows an example of putting a halo on (but not using it in the way we intend to): https://www.youtube.com/watch?v=pcenAa7oNII
