### ISSUE TITLE
Twine Status Window Screen Space

### ISSUE THREAD

**Issue by cpimhoff** [mjavaly/Prairie#90]
The Twine Status box has some strange behavior and funky margins on different large and small screen sizes.

**Comment by grahamearley** [comment]
We should standardize all our HUD sizing. Let's talk about it at our next meeting

**Comment by cpimhoff** [comment]
I'm happy to just do this based on the same margin logic I wrote for the player toolbar -- we already defined the regions of the screen we each have access to.
