### ISSUE TITLE
Check status of TwineJson dependency -- ensure that it always works..

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#93]
Does TwineJson not work for large Twine stories? Can we fix it somehow?

Let's find out.

**Comment by grahamearley** [comment]
If we can't get TwineJson to work consistently, we could also look into writing our own parser for one of the default Twine export styles.

**Comment by brennan724** [comment]
We could.  It wouldn't be fun.  Would it not be easier to PR his with a non json.stringify method?

**Comment by grahamearley** [comment]
Probably, but I still have to look into how that works. Just putting this here as a note for what we could do if this doesn't work out.

**Comment by grahamearley** [comment]
Here's an alternative: https://github.com/lazerwalker/twison

This one appears to work for more complex/big Twine stories. To use it, we would just need to modify our importer to use the slightly different naming that this json output uses. Also, it includes the  part that links to the next nodes (e.g. `[[LINK]]`) in the body text of each node, so we'd need to remove that too.

The biggest downside with this one is that it doesn't automatically download. It looks like users would have to copy and paste json text into a text editor and save it as a .json file.

However, perhaps we could just tell users to copy and paste the text into a new text input box in the Twine Importer. This might actually be easier? Then you wouldn't have to download a file and import it into Unity; you'd just have to copy and paste some text.

**Comment by grahamearley** [comment]
Started transition to Twison in PR #121
