### ISSUE TITLE
Make TwineNode inspector GUI read-only

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#95]
Make the inspector only show title, body text, and maybe a link to the parent / children.

**Comment by brennan724** [comment]
Make 'Name', 'Tags', 'Children', 'Parents' unchangeable (links for the last two).  Allow 'content' to be changeable (make into a larger text box if possible).

**Comment by grahamearley** [comment]
@brennan724 My pending changes that were blocking you are in #91 now, so you're good to go as soon as that gets pulled in!
