### ISSUE TITLE
🎨 Custom GUI! Next Twine Node interaction edition

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#99]

**Comment by cpimhoff** [comment]
Our current one is looking pretty swell - not sure how much more I feel needs to be done

**Comment by grahamearley** [comment]
I'm actually going to take this, since it's similar to #83. I'll rename it and work on having it hold multiple TwineNodeInteractions.

Going to close this issue since it's pretty much contained in #83.
